version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "monthly"
      day: "sunday"
    assignees:
      - "dennykorsukewitz"
    reviewers:
      - "dennykorsukewitz"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    assignees:
      - "dennykorsukewitz"
    reviewers:
      - "dennykorsukewitz"